sudo: required
services:
  - docker

before_install:
  - docker build -t davidg-fnd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true davidg-fnd/docker-react npm run test -- --coverage
